### ISSUE TITLE
Maintainers Wanted [from README]

### ISSUE THREAD

**Issue by sungam3r** [ArieGato/serilog-sinks-rabbitmq#124]
Hi. I can help with support for this repo. I'm familiar with both Serilog ecosystem, RabbitMQ and have experience in OSS, see my [profile](https://github.com/sungam3r).

Plan:
- Cleanup code
- Move to modern NET and tooling
- Sort out issues and PRs
- Publish fresh nuget version

**Comment by lyng-dev** [comment]
Hey - sounds great. I am on vacation right now, but let's talk after Easter ? Thx

**Comment by sungam3r** [comment]
ok

**Comment by sungam3r** [comment]
ping @lyng-dev

**Comment by lyng-dev** [comment]
@sungam3r Hi, sorry for the late reply. I'd be very happy to pass over custodianship for this project, since I simply don't have time any more.

Let's have a talk on Gitter: https://gitter.im/serilog-sinks-rabbitmq/Lobby

**Comment by sungam3r** [comment]
ok
