### ISSUE TITLE
Merging and publishing an improved project fork

### ISSUE THREAD

**Issue by sarunasil** [ArieGato/serilog-sinks-rabbitmq#125]
Hello,
I've been looking to use this solution as part of my projects but found it having poor SSL support capabilities. I saw there is an ssl-improvements branch already created but I believe there isn't any real work going on it since it's been quite a while since any new commits happened on it and the work is unfinished. Fortunately, I found a fork of this project  https://github.com/gekiss/serilog-sinks-rabbitmq which already has implemented these features and has some other improvements too.

Would you possibly consider merging in the fork features and releasing a new version of the nuget? I'm sure it would be beneficial for everyone. In my case particularly, it would avoid me maintaining [the forked](https://github.com/gekiss/serilog-sinks-rabbitmq) and locally build assets. 

Thanks!

**Comment by sungam3r** [comment]
Related - #124

**Comment by ArieGato** [comment]
@sarunasil Working on it.
