### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by sungam3r** [ArieGato/serilog-sinks-rabbitmq#128]
Hi. I'm glad to see new maintainer for this sink. I can make PR with configured GitHub actions as I already did for [destructurama](https://github.com/destructurama) projects.

**Comment by sungam3r** [comment]
Or you can just copy-paste all https://github.com/destructurama/attributed/tree/master/.github folder . You need slightly change paths in labeler.yml and add repo secret named NUGET_AUTH_TOKEN.

**Comment by sungam3r** [comment]
I see #129. It's a step in the right direction.

**Comment by ArieGato** [comment]
I’ll have a look at the build you referenced. For now the integration tests are running against a rabbitmq instance. And the package is published to my github feed.
