### ISSUE TITLE
Upgrade serilog to 3.1.1 gives errors

### ISSUE THREAD

**Issue by zelda1link3** [ArieGato/serilog-sinks-rabbitmq#130]
When upgrading to the newest serilog the rawformatting is deleted.
I think this needs to be removed and changed to compactjsonformatter.

see:

https://github.com/serilog/serilog/pull/1808/commits/8c5914d8284c60b54f9fded30f936bd15ca14a55

**Comment by zelda1link3** [comment]
I see that you already changed it in the #125 . Is there an eta on a new version?

**Comment by ArieGato** [comment]
I cannot give an estimate right now. I did some refactoring and I want to make sure everything is working as expected. My best guess would be in about two weeks or so.

**Comment by zelda1link3** [comment]
That would be great for us. Can u use any help in testing or refactoring if so please let me know so i can help.

**Comment by ArieGato** [comment]
I setup the ci build to push packages to the [github feed](https://github.com/ArieGato/serilog-sinks-rabbitmq/pkgs/nuget/Serilog.Sinks.RabbitMQ). Feel free to give it try.

**Comment by ArieGato** [comment]
@zelda1link3 

The first prerelease has been published on nuget.org: https://www.nuget.org/packages/Serilog.Sinks.RabbitMQ/7.0.0-pre.44

Please let us know if you find any issues with it.

**Comment by sungam3r** [comment]
Closed as completed and due to lack of feedback.
