### ISSUE TITLE
Add API approval tests

### ISSUE THREAD

**Issue by sungam3r** [ArieGato/serilog-sinks-rabbitmq#141]
See serilog or destructurama repos as examples. 

@ArieGato I can post PR if ok.

**Comment by ArieGato** [comment]
What the purpose for this? Can you explain a little?

**Comment by ArieGato** [comment]
So basically it's to detect breaking changes? Sounds like a good plan then.

**Comment by sungam3r** [comment]
So basically it's to detect breaking changes?

Yes.
