### ISSUE TITLE
Simplify versioning

### ISSUE THREAD

**Issue by sungam3r** [ArieGato/serilog-sinks-rabbitmq#145]
See https://github.com/ArieGato/serilog-sinks-rabbitmq/pull/142/files#r1478184786

**Comment by ArieGato** [comment]
@sungam3r can the versioning be simplefied without gitversion?

**Comment by sungam3r** [comment]
Yes. MinVer package can handle versioning. See this one https://github.com/destructurama/by-ignoring/blob/master/src/Directory.Build.props#L35 and then https://github.com/destructurama/by-ignoring/blob/master/.github/workflows/publish-release.yml - there is no any jumping around versioning like here https://github.com/ArieGato/serilog-sinks-rabbitmq/blob/master/.github/workflows/publish-release.yml#L55-L72

**Comment by ArieGato** [comment]
Sounds good.
