### ISSUE TITLE
ci build fails on Approval check

### ISSUE THREAD

**Issue by ArieGato** [ArieGato/serilog-sinks-rabbitmq#151]
The ci build fails on the public API approval test.

~It appears to be caused by the release configuration build?~

```
[xUnit.net 00:00:01.85]       System.Exception : Source information not available, make sure you are compiling with full debug information. Frame: ApiApprovalTests.PublicApi_Should_Not_Change_Unintentionally
```

@sungam3r Any ideas?

**Comment by sungam3r** [comment]
I'll take a look today. I think the difference is sdk-related. Try print API string on CI manually and then compare it with locally generated.

**Comment by sungam3r** [comment]
Related https://github.com/shouldly/shouldly/issues/574

**Comment by sungam3r** [comment]
Bingo! It failed only for net48. Now approval test runs only on net8.

**Comment by ArieGato** [comment]
Ahhh, great work!
