### ISSUE TITLE
V7 release

### ISSUE THREAD

**Issue by sungam3r** [ArieGato/serilog-sinks-rabbitmq#153]
@ArieGato I would like to post some PRs before v7 if you OK.

**Comment by ArieGato** [comment]
What did you have in mind?

And is there something in github to structure these things. Some sort of Release planning

**Comment by sungam3r** [comment]
Some more cleanup, reorganize a bit project structure, CI changes. Maybe some API changes. 

GitHub has projects feature but I don't use it. As I have seen these years devs just track such things as ordinal issues.

**Comment by ArieGato** [comment]
Well, then I would like to see them as issues so we can discuss them on forehand.

**Comment by ArieGato** [comment]
@sungam3r You mentioned something about the ci changes. What did you have in mind?

**Comment by sungam3r** [comment]
Changes in versioning - more simple way to set version. Changes in release triggers. Running dotnet format. I can not tell exactly the whole set of changes. I can do this in the near future.

**Comment by ArieGato** [comment]
@sungam3r Do you want to do some more cleaning before release v7? I was thinking about releasing.

**Comment by sungam3r** [comment]
Yes.

**Comment by ArieGato** [comment]
@sungam3r There are some merge conflicts that need to be resolved.

**Comment by ArieGato** [comment]
@sungam3r  Are we ready for a v7 release?

**Comment by sungam3r** [comment]
I was away from my PC, let me check some stuff tomorrow monday and I'll return with answer.

**Comment by sungam3r** [comment]
The first thing I would like to close in v7 is #155.

**Comment by sungam3r** [comment]
I pushed some PRs with changes. I think I can make a few more (2-3) when merging those and all things will be ready for release.

**Comment by sungam3r** [comment]
For now I'm interested in #179.

**Comment by sungam3r** [comment]
Tomorrow I'll publish one more PR with TFM changes and I think that one will be the last for v7.

**Comment by sungam3r** [comment]
I'm done here and ready for release.

**Comment by sungam3r** [comment]
Oh, one more thing.

**Comment by sungam3r** [comment]
#199

**Comment by sungam3r** [comment]
@ArieGato Would you like me to make new release https://github.com/ArieGato/serilog-sinks-rabbitmq/releases/new or will you do it yourself?

**Comment by sungam3r** [comment]
Just use tag `v7.0.0` , prev tag 6.0.0 and `generate release notes` button.

**Comment by ArieGato** [comment]
If you could do it the first time, would be nice. I would like to know what options you select, so I can do it myself the next time.

**Comment by sungam3r** [comment]
![изображение](https://github.com/ArieGato/serilog-sinks-rabbitmq/assets/21261007/83933550-9dc0-43e9-9359-1ad9f15e652d)

![изображение](https://github.com/ArieGato/serilog-sinks-rabbitmq/assets/21261007/0b8d6b07-7c1e-4443-9d99-8139255f4d9d)

**Comment by sungam3r** [comment]
https://github.com/ArieGato/serilog-sinks-rabbitmq/releases/tag/v7.0.0

Generate release notes button does the most work. After taht you may change generated text in any way you want

**Comment by sungam3r** [comment]
![изображение](https://github.com/ArieGato/serilog-sinks-rabbitmq/assets/21261007/4331376e-b191-4cc9-a0eb-519192cb7f01)

**Comment by sungam3r** [comment]
![изображение](https://github.com/ArieGato/serilog-sinks-rabbitmq/assets/21261007/08ce136b-1674-4130-8776-3c5fe4162c1c)

**Comment by sungam3r** [comment]
https://github.com/ArieGato/serilog-sinks-rabbitmq/releases/tag/v7.0.0

Note attached files:
![изображение](https://github.com/ArieGato/serilog-sinks-rabbitmq/assets/21261007/635c9854-2b93-4fde-8f52-6a2042febfe0)

**Comment by sungam3r** [comment]
https://www.nuget.org/packages/Serilog.Sinks.RabbitMQ :
![изображение](https://github.com/ArieGato/serilog-sinks-rabbitmq/assets/21261007/499349eb-d742-46e1-8436-c23cf157308a)

**Comment by sungam3r** [comment]
![изображение](https://github.com/ArieGato/serilog-sinks-rabbitmq/assets/21261007/f8b83225-26ec-4b81-af12-6280c88bc763)

**Comment by ArieGato** [comment]
Thnx @sungam3r ! Thanks for all the help and guidance!

**Comment by sungam3r** [comment]
Hah. Just noticed. You do not mind if I add myself to the list of authors?
![изображение](https://github.com/ArieGato/serilog-sinks-rabbitmq/assets/21261007/85c9e6f6-5eb5-4118-8646-ed1802d65ceb)
