### ISSUE TITLE
Specify MinVerTagPrefix for MinVer package

### ISSUE THREAD

**Issue by ArieGato** [ArieGato/serilog-sinks-rabbitmq#171]
The MinVerPrefix project property is missing.

`<MinVerTagPrefix>v</MinVerTagPrefix>`

**Comment by sungam3r** [comment]
@ArieGato It is not necessary to use some kind of prefix at all. Many projects use semantic versions in tags as is, for example 1.2.3. It's a matter of taste; up to you.

**Comment by sungam3r** [comment]
And this was definitely not a bug.
