### ISSUE TITLE
Fix Test for Ssl Certificate authentication

### ISSUE THREAD

**Issue by ArieGato** [ArieGato/serilog-sinks-rabbitmq#183]
The user name and password of the Configuration need to be empty to test this correctly.

**Comment by sungam3r** [comment]
You can create issues based on comments so context/history is preserved
![изображение](https://github.com/ArieGato/serilog-sinks-rabbitmq/assets/21261007/cfcc62b2-b802-4cfa-b701-8ac0b48bf683)

**Comment by ArieGato** [comment]
Is replaced by #184
