### ISSUE TITLE
Should be noted in breaking changes in changelog.

### ISSUE THREAD

**Issue by sungam3r** [ArieGato/serilog-sinks-rabbitmq#194]
Should be noted in breaking changes in changelog.

_Originally posted by @sungam3r in https://github.com/ArieGato/serilog-sinks-rabbitmq/issues/166#issuecomment-2000242407_

**Comment by ArieGato** [comment]
What is breaking?

**Comment by sungam3r** [comment]
Reference/require new major version of dependency.

**Comment by ArieGato** [comment]
I tried to find out what was breaking about the package, but I can’t seem to find it.

**Comment by sungam3r** [comment]
https://github.com/serilog/serilog-sinks-periodicbatching/pull/66

**Comment by sungam3r** [comment]
![изображение](https://github.com/ArieGato/serilog-sinks-rabbitmq/assets/21261007/ee472ac8-d1f9-41a3-b075-ef951d988c00)

**Comment by ArieGato** [comment]
I see. Some sinks will stop to work.
