### ISSUE TITLE
Publish 7.0.1 release with bumped dependencies

### ISSUE THREAD

**Issue by sungam3r** [ArieGato/serilog-sinks-rabbitmq#202]

**Comment by ArieGato** [comment]
@sungam3r how do I configrm that sourcelink is still working?

**Comment by sungam3r** [comment]
Use 7.0.1 in some project and step into its method.

**Comment by ArieGato** [comment]
Release has been started

**Comment by sungam3r** [comment]
Another option to check SourceLink - NugetPackageExplorer
![изображение](https://github.com/ArieGato/serilog-sinks-rabbitmq/assets/21261007/bbd105e9-1be7-4c64-b6a7-3371b4db88b0)
