### ISSUE TITLE
Debug logs are not being sent to RabbitMQ, all other yes

### ISSUE THREAD

**Issue by ddcavalheiro** [ArieGato/serilog-sinks-rabbitmq#206]
**Describe the bug**
Debug type logs not being sent RabbitMQ, only other like information, warning, errors...

**To Reproduce**
RabbitMQ 3.13.0
Package version 7.0.1 (also tested with 7.0.0)

_logger.LogDebug("Sample text to Log");
or
Log.Debug("Debug log test");

none works! for other sinks they are being sent, just RabbitMQ they aren't.

I am using it in a aspnetcore background service and configuration in a appsettings file.

Also tested with sample project provided in this repo and same behavior is happening.

Anyone faced that before? Sorry if I didn't follow the rules in this post, first time ever...

**Comment by ArieGato** [comment]
I found the issue. The default LevelSwitch of the sink is set to Information. I'll change thisa to comply with the default used in Serilog. In the mean time as a work around you can add `"levelSwitch": "Debug"` to the appsettings file.

**Comment by ArieGato** [comment]
@ddcavalheiro I just released 7.0.2. It should fix this issue.
