### ISSUE TITLE
Set BasicProperties delivery mode for BasicPublish

### ISSUE THREAD

**Issue by Andre-Meira** [ArieGato/serilog-sinks-rabbitmq#215]
Hi.

I’d like to understand why RabbitMQDeliveryMode only enables persistence for the exchange and not for both the published message and the exchange.

In this scenario, it seems like there’s a chance of message loss, which I’m concerned about.

This is my first time working with this project, and I haven't found any related issues so far.

**Comment by ArieGato** [comment]
@Andre-Meira It apears this was lost during refactoring the library.

**Comment by Andre-Meira** [comment]
Hi @ArieGato. 

I'm not sure how this property was handled before the library was refactored, but I think it would be useful to have a configuration based on RabbitMQ’s IBasicProperties to set message parameters like:

- DeliveryMode
- Expiration
- Priority
- CorrelationId

I’d be glad to help with any improvements on this.

**Comment by ArieGato** [comment]
thanks for the offer, but I have an idea how to solve this. For this I'm waiting for RabbitMQ client 7.x. That will also solve #211.

**Comment by Andre-Meira** [comment]
Ok, thanks @ArieGato.

I'm waiting for the resolution.

**Comment by ArieGato** [comment]
@Andre-Meira The issue with persistence has been fixed in v7.0.3

Setting the other properties of IBasicProperties will come in v8.

**Comment by Andre-Meira** [comment]
The issue has been successfully resolved.

Tks...
